swagger: "2.0"
info:
  description: "All the known endpoints for the VRChat API are listed below. While using the API you are required to follow VRChat's Term of Service. Abuse of the API may result in account termination."
  version: ""
  title: "Endpoints"
  termsOfService: "https://vrchat.com/legal"
host: "api.vrchat.cloud"
basePath: "/api/1/"
tags:
- name: "Miscellaneous"
  description: ""
- name: "User"
  description: "Endpoints controlling the current authenticated user."
schemes:
- "https"
- "http"
paths:
  /config:
    get:
      tags:
      - "Miscellaneous"
      summary: "Remote Config."
      description: ""
      operationId: "config"
      produces:
      - "application/json"
      responses:
        200:
          description: "Invalid input"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/RemoteConfig"
  /auth/user:
    get:
      tags:
      - "User"
      summary: "Fetch current user information."
      description: "Fetching the user information requires the apiKey parameter and Authorization header"
      operationId: "auth/user"
      produces:
      - "application/json"
      parameters:
      - name: "apiKey"
        in: "query"
        description: "The required apiKey."
        default: "JlE5Jldo5Jibnk5O5hTx6XVqsJu4WJ26"
        required: true
        type: "string"
      - name: "Authorization"
        in: "header"
        description: "The basic authentication defining the current user. Base64 encode: username:password"
        default: "Basic dXNlcm5hbWU6cGFzc3dvcmQ="
        required: true
        type: "string"
        format: "base64"
      responses:
        default:
          description: "successful operation"

definitions:
  RemoteConfig:
    type: "object"
    properties:
      messageOfTheDay:
        type: "string"
      timeOutWorldId:
        type: "string"
      gearDemoRoomId:
        type: "string"
      releaseServerVersionStandalone:
        type: "string"
      downloadLinkWindows:
        type: "string"
      releaseAppVersionStandalone:
        type: "string"
      devAppVersionStandalone:
        type: "string"
      devServerVersionStandalone:
        type: "string"
      devDownloadLinkWindows:
        type: "string"
      currentTOSVersion:
        type: "string"
      releaseSdkUrl:
        type: "string"
      releaseSdkVersion:
        type: "string"
      devSdkUrl:
        type: "string"
      devSdkVersion:
        type: "string"
      whiteListedAssetUrls:
        type: "null"
      clientApiKey:
        type: "string"
      viveWindowsUrl:
        type: "string"
      sdkUnityVersion:
        type: "string"
      hubWorldId:
        type: "string"
      homeWorldId:
        type: "string"
      tutorialWorldId:
        type: "string"
      disableEventStream:
        type: "boolean"
      disableAvatarGating:
        type: "boolean"
      disableFeedbackGating:
        type: "boolean"
      disableRegistration:
        type: "boolean"
      disableUpgradeAccount:
        type: "boolean"
      disableCommunityLabs:
        type: "boolean"
      plugin:
        type: "string"
      sdkNotAllowedToPublishMessage:
        type: "string"
      sdkDeveloperFaqUrl:
        type: "string"
      sdkDiscordUrl:
        type: "string"
      notAllowedToSelectAvatarInPrivateWorldMessage:
        type: "string"
      userVerificationTimeout:
        type: "integer"
      userUpdatePeriod:
        type: "integer"
      userVerificationDelay:
        type: "integer"
      userVerificationRetry:
        type: "integer"
      worldUpdatePeriod:
        type: "integer"
      moderationQueryPeriod:
        type: "integer"
      defaultAvatar:
        type: "integer"
      dynamicWorldRows:
        type: "null"
      address:
        type: "string"
      contactEmail:
        type: "string"
      supportEmail:
        type: "string"
      jobsEmail:
        type: "string"
      copyrightEmail:
        type: "string"
      moderationEmail:
        type: "string"
      disableEmail:
        type: "boolean"
      appName:
        type: "string"
      serverName:
        type: "string"
      deploymentGroup:
        type: "string"
      buildVersionTag:
        type: "string"
      apiKey:
        type: "string"

externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
